apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-devops-trab.fullname" . }}-configmap
  labels:
    {{- include "chart-devops-trab.labels" . | nindent 4 }}
data:
  # Adicione seus dados aqui
  # Exemplo:
  database_url: {{ .Values.config.database_url | quote }}
  api_key: {{ .Values.config.api_key | quote }}
