apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-devops-trab.fullname" . }}-secret
  labels:
    {{- include "chart-devops-trab.labels" . | nindent 4 }}
type: Opaque
data:
  # Adicione seus dados aqui, eles devem ser codificados em base64
  # Exemplo:
  username: {{ .Values.secret.username | b64enc | quote }}
  password: {{ .Values.secret.password | b64enc | quote }}
